# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    open-pull-requests-limit: 999
    ignore:
      # Breaks with asynchronous `useEffect()`
      - dependency-name: '@types/react'
        versions: '>=16.0.0'
      - dependency-name: '@types/react-dom'
        versions: '>=16.0.0'
      - dependency-name: 'react'
        versions: '>=16.0.0'
      - dependency-name: 'react-dom'
        versions: '>=16.0.0'
      # Breaks font rendering
      - dependency-name: 'styled-components'
        versions: '>=5.0.0'
      # react-scripts blocks v5+
      - dependency-name: 'typescript'
        versions: '>=5.0.0'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-*'
          - 'styled-components'
      cloudflare:
        patterns:
          - '@cloudflare/*'
          - 'wrangler'
        exclude-patterns:
          - '@cloudflare/workers-types'
      typescript:
        patterns:
          - '@types/*'
          - '@cloudflare/workers-types'
          - 'typescript'
      code-management:
        patterns:
          - 'prettier'
          - '@demosjarco/prettier-config'
          - 'eslint'
          - 'eslint-config-*'
          - 'eslint-plugin-*'
          - '@typescript-eslint/*'